Fix audio length
sepandhaghighi/mytimer pull request #40
Opened 2023-07-25 17:30 UTC by sadrasabouri

#### Reference Issues/PRs
#39 
#### What does this implement/fix? Explain your changes.
Below audio files have been looped to have length between `1.5`s - `2.5`s:
- `3.wav`
- `4.wav`
- `5.wav`
- `6.wav`
- `7.wav`
- `8.wav`
- `9.wav`
- `10.wav`
- `11.wav`

2023-07-26 09:15 UTC, sepandhaghighi requested changes
@sadrasabouri Well done 🚀 

Please take a look at my comments and also:

- Update `TONES.md` (**duration** and **size** sections)

2023-07-26 09:15 UTC, sepandhaghighi commented on CHANGELOG.md
> +- alarms' length
- alarms' length modified

2023-07-27 08:42 UTC, sadrasabouri commented
It's now ready for your review @sepandhaghighi

2023-07-28 13:37 UTC, sepandhaghighi approved these changes
🚀

2023-07-28 13:39 UTC, merged